// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vacinacao.Infrastructure;

#nullable disable

namespace Vacinacao.Infrastructure.Migrations
{
    [DbContext(typeof(VacinacaoDbContext))]
    partial class VacinacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vacinacao.Domain.Campanha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Doenca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("doenca");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("especie");

                    b.Property<DateOnly>("Fim")
                        .HasColumnType("date")
                        .HasColumnName("fim");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<bool>("Obrigatoria")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatoria");

                    b.Property<int>("ValidadeMeses")
                        .HasColumnType("integer")
                        .HasColumnName("validade_meses");

                    b.HasKey("Id")
                        .HasName("pk_campanha");

                    b.HasIndex("Especie", "Obrigatoria")
                        .HasDatabaseName("ix_campanha_especie_obrigatoria");

                    b.ToTable("campanha", null, t =>
                        {
                            t.HasCheckConstraint("ck_campanha_periodo", "fim >= inicio");

                            t.HasCheckConstraint("ck_campanha_validade", "validade_meses BETWEEN 1 AND 60");
                        });
                });

            modelBuilder.Entity("Vacinacao.Domain.RegistroVacinacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampanhaId")
                        .HasColumnType("uuid")
                        .HasColumnName("campanha_id");

                    b.Property<string>("CrmvVeterinario")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("crmv_veterinario");

                    b.Property<DateOnly>("DataAplicacao")
                        .HasColumnType("date")
                        .HasColumnName("data_aplicacao");

                    b.Property<string>("Doenca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("doenca");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("especie");

                    b.Property<string>("LoteVacina")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lote_vacina");

                    b.Property<string>("Propriedade")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("codigo_propriedade");

                    b.Property<int>("QuantidadeAnimais")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_animais");

                    b.Property<DateOnly>("ValidaAte")
                        .HasColumnType("date")
                        .HasColumnName("valida_ate");

                    b.HasKey("Id")
                        .HasName("pk_registro_vacinacao");

                    b.HasIndex("CampanhaId")
                        .HasDatabaseName("ix_registro_vacinacao_campanha_id");

                    b.HasIndex("Propriedade", "Especie")
                        .HasDatabaseName("ix_registro_vacinacao_codigo_propriedade_especie");

                    b.ToTable("registro_vacinacao", null, t =>
                        {
                            t.HasCheckConstraint("ck_registro_quantidade", "quantidade_animais > 0");
                        });
                });

            modelBuilder.Entity("Vacinacao.Domain.RegistroVacinacao", b =>
                {
                    b.HasOne("Vacinacao.Domain.Campanha", null)
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registro_vacinacao_campanha_campanha_id");
                });
#pragma warning restore 612, 618
        }
    }
}
